const mongoose = require("mongoose");
const userSchema= new Schema({
    username:{
        type:String,
        required:true,
        unique:true,
        trim:true,
        minlength:3,
        maxlength:30
    },
    email:{
        type:String,
        required:true,
    },
    password:{
        type:String,
        required:true,
        minlength:8,
    },
    name:{
        type:String,
        required:true,
    },
    DOB:{
        type:Date,
        required:true,
    },
    Gender:{
        type:String,
        required:true,
        enum:['Male','Female','Others']
    },
    treeplanted:{
        type:Number,
        default:0
    },
    level:{
        type:Number,
        default:1
    },
    points:{
        type:Number,
        default:0
    },
    co2saved:{
        type:Number,
        default:0
    },
    profileImage:{
        type:String,
        default:'https://cdn-icons-png.flaticon.com/512/149/149071.png'
    },
    recycled:{
        type:Number,
        default:0
    }
})
module.exports=mongoose.model('User',userSchema);